### ISSUE TITLE
not working when using template tags inside html tags

### ISSUE THREAD

**Issue by Knotschi** [zertosh/jstify#2]
```
<input type="checkbox"<% if(selected){ %> checked="checked"<% } %> />
```

is not working.

**Comment by jlambe** [comment]
Hello, I'm still having a parse issue when compiling this line of code from my template:
```html
 <input class="toggle" type="checkbox" checked="<%= done ? 'checked' : '' %>">
```
The compiler is not saying there is an issue but it completely ignore the line `<%= done ? 'checked' : '' %>` causing the input to be always checked because the attribute name is rendered.

I tried the `noMinify` option but without success. Here is a npm script that I use:
```bash
"watchify -t [ jstify --noMinify ] js/main.js -o js/bundle.js -dv"
```

**Comment by Knotschi** [comment]
in your code example the checked attribute should always be rendered because it is outside of the "done" condition. checked="checked" is the same as checked="" (the cheked attribute doesnt need a value). 
try:

```
<input class="toggle" type="checkbox"<%= done ? ' checked' : '' %>>
```

**Comment by jlambe** [comment]
Well now using this code I have a parse error... Is your first code example working now, the one you used to start this issue?

**Comment by Knotschi** [comment]
I havent tried because im not using jstify anymore.

**Comment by jlambe** [comment]
Well it doesn't work for the moment. It seems we can only output values using this module. Too bad.

**Comment by zertosh** [comment]
Sorry, `noMinify` was removed in favor of setting `minifierOpts` to `false`. But turns out that setting `minifierOpts` via the command-line is kinda hard because browserify passes the value as a string. So instead of doing some weird casting `'false'` to `false`, I added back `noMinify`. Just published as jstify@0.9.0

**Comment by jlambe** [comment]
I'm updating my project. Is this command right then:
```js
"scripts": {
        "watch": "watchify -t [ jstify --noMinify ] js/main.js -o js/bundle.js -dv"
    }
```

**Comment by zertosh** [comment]
@jbielick Yup

**Comment by jlambe** [comment]
It's working smoothly now, thanks!

**Comment by dannycochran** [comment]
anyway to get this working with grunt? I have:

```
    browserify: {
      dist: {
        src: app + '/build/build.js',
        dest: 'dist/build.js',
        options: {
          transform: ['jstify'],
          noMinify: true,
        }
      }
    },
```

**Comment by zertosh** [comment]
@dannycochran Can you open a new issue? I don't use grunt, but I think what you have to do is:


```
   browserify: {
      dist: {
        src: app + '/build/build.js',
        dest: 'dist/build.js',
        options: {
          transform: [['jstify', {noMinify: true}]],
        }
      }
    },
```

**Comment by dannycochran** [comment]
that does it. thanks!
